steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/terraform-project-369818/myapp1', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/terraform-project-369818/myapp1']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'myapp', '--image', 'gcr.io/terraform-project-369818/myapp1', '--region', 'europe-west1', '--platform', 'managed', '--port', '80']
images:
- gcr.io/terraform-project-369818/myapp1